import Link from "next/link";
import { ArrowUpRight, Github, Linkedin } from "lucide-react";
import { AppShell } from "@/components/app-shell";
import { Badge, Card, ProgressBar, SectionLabel, StreakIndicator } from "@/components/ui";
import { challengeProgress, currentStreak, student } from "@/lib/mock-data";

export default function HomePage() {
  return <AppShell><div className="page space-y-9"><div className="flex items-start justify-between"><div><Badge tone="signal">60 day challenge</Badge><h1 className="mt-5 text-4xl font-semibold leading-[0.98] tracking-[-0.055em] text-paper">Build every day.<br />Show the work.</h1></div><div className="grid size-11 place-items-center rounded-full border border-line font-mono text-xs text-signal">{student.avatar}</div></div><p className="max-w-sm text-sm leading-6 text-muted">A public build streak for Indian students who want a body of work—not just another certificate.</p><Card className="p-4"><div className="flex items-start justify-between"><div><SectionLabel>Challenge progress</SectionLabel><p className="mt-2 font-mono text-2xl font-semibold">{challengeProgress.completedDays}<span className="text-muted">/{challengeProgress.totalDays}</span></p></div><StreakIndicator days={currentStreak.days} compact /></div><div className="mt-5"><ProgressBar value={challengeProgress.completedDays} /></div><Link href="/dashboard" className="mt-4 flex items-center justify-between border-t border-line pt-3 font-mono text-[11px] uppercase tracking-eyebrow text-muted">View your progress <ArrowUpRight size={14} className="text-signal" /></Link></Card><div><SectionLabel>How it works</SectionLabel><div className="mt-4 grid gap-px bg-line"><div className="bg-ink p-4"><Github size={18} className="text-signal" /><p className="mt-5 font-mono text-xs text-paper">01 / Commit</p><p className="mt-1 text-xs leading-5 text-muted">Ship a meaningful piece of work.</p></div><div className="bg-ink p-4"><Linkedin size={18} className="text-signal" /><p className="mt-5 font-mono text-xs text-paper">02 / Share</p><p className="mt-1 text-xs leading-5 text-muted">Write about what you learned.</p></div></div></div><Link href="/day/12" className="flex h-11 w-full items-center justify-center gap-2 rounded-sm bg-signal px-4 text-sm font-semibold text-graphite transition hover:bg-paper">Start day 12 <ArrowUpRight size={16} /></Link></div></AppShell>;
}
